import { countryCodeToIso3 } from "./countryCodesISO";

// Map ISO3 codes to language codes
const iso3ToLanguage = {
  IND: "hi", // Hindi
  MDA: "ro", // Romanian
  ISR: "he", // Hebrew
  USA: "en", // English
  GBR: "en", // English
  CHN: "zh", // Chinese
  RUS: "ru", // Russian
  SAU: "ar", // Arabic
  EGY: "ar", // Arabic
  THA: "th", // Thai
  LKA: "si", // Sinhala
  PAK: "ur", // Urdu
  BGD: "bn", // Bengali
  VNM: "vi", // Vietnamese
  IDN: "id", // Indonesian
  KOR: "ko", // Korean
  JPN: "ja", // Japanese
};

// RTL languages
const rtlLanguages = ["ar", "he", "fa", "ur"];

// Default translations for all languages
const defaultTranslations = {
  // Common buttons
  save: "Save",
  cancel: "Cancel",
  close: "Close",
  submit: "Submit",
  edit: "Edit",
  delete: "Delete",
  add: "Add",

  // Form labels
  name: "Name",
  email: "Email",
  phone: "Phone",
  address: "Address",
  city: "City",
  country: "Country",

  // PDF Form labels
  formEditor: "Form Editor",
  formDetails: "Form Details",
  formName: "Form Name",
  worker: "Worker",
  document: "Document",
  category: "Category",
  note: "Note",

  // PDF actions
  loadingTemplate: "Loading template...",
  pdfEditor: "PDF Editor",
  generateDocument: "Generate Document",
  download: "Download",
  print: "Print",

  // Signature dialog
  createSignature: "Add Signature",
  typeSignature: "Type",
  drawSignature: "Draw",
  typeHere: "Type your signature here",
  clear: "Clear",
  signHere: "Click to sign",

  // Errors
  error: "Error",
  errorMessage: "Please add a signature",
};

// Hebrew translations
const hebrewTranslations = {
  save: "שמור",
  cancel: "ביטול",
  close: "סגור",
  submit: "שלח",
  edit: "ערוך",
  delete: "מחק",
  add: "הוסף",

  name: "שם",
  email: "אימייל",
  phone: "טלפון",
  address: "כתובת",
  city: "עיר",
  country: "מדינה",

  formEditor: "עורך טפסים",
  formDetails: "פרטי הטופס",
  formName: "שם הטופס",
  worker: "עובד",
  document: "מסמך",
  category: "קטגוריה",
  note: "הערה",

  loadingTemplate: "טוען תבנית...",
  pdfEditor: "עורך PDF",
  generateDocument: "צור מסמך",
  download: "הורד",
  print: "הדפס",

  createSignature: "הוסף חתימה",
  typeSignature: "הקלדה",
  drawSignature: "ציור",
  typeHere: "הקלד את חתימתך כאן",
  clear: "נקה",
  signHere: "לחץ לחתימה",

  error: "שגיאה",
  errorMessage: "נא להוסיף חתימה",
};

// Arabic translations
const arabicTranslations = {
  save: "حفظ",
  cancel: "إلغاء",
  close: "إغلاق",
  submit: "إرسال",
  edit: "تعديل",
  delete: "حذف",
  add: "إضافة",

  name: "الاسم",
  email: "البريد الإلكتروني",
  phone: "الهاتف",
  address: "العنوان",
  city: "المدينة",
  country: "البلد",

  formEditor: "محرر النماذج",
  formDetails: "تفاصيل النموذج",
  formName: "اسم النموذج",
  worker: "العامل",
  document: "المستند",
  category: "الفئة",
  note: "ملاحظة",

  loadingTemplate: "جاري تحميل القالب...",
  pdfEditor: "محرر PDF",
  generateDocument: "إنشاء مستند",
  download: "تنزيل",
  print: "طباعة",

  createSignature: "إضافة توقيع",
  typeSignature: "كتابة",
  drawSignature: "رسم",
  typeHere: "اكتب توقيعك هنا",
  clear: "مسح",
  signHere: "انقر للتوقيع",

  error: "خطأ",
  errorMessage: "الرجاء إضافة توقيع",
};

// Language specific translations
const translations = {
  en: defaultTranslations,
  he: hebrewTranslations,
  ar: arabicTranslations,
};

/**
 * Get language code from country code
 * @param {string} countryCode - Country code (ISO numeric)
 * @returns {string} Language code (ISO 639-1)
 */
export const getLanguageFromCountryCode = (countryCode) => {
  try {
    // Convert country code to ISO3
    const iso3 = countryCodeToIso3(countryCode);
    console.log(`Country code ${countryCode} maps to ISO3 ${iso3}`);

    // Get language from ISO3
    const language = iso3ToLanguage[iso3] || "en";
    console.log(`ISO3 ${iso3} maps to language ${language}`);

    return language;
  } catch (error) {
    console.error("Error getting language from country code:", error);
    return "en";
  }
};

/**
 * Check if a language is RTL
 * @param {string} language - Language code (ISO 639-1)
 * @returns {boolean} Is RTL
 */
export const isRTLLanguage = (language) => {
  return rtlLanguages.includes(language);
};

/**
 * Get translations for a specific language
 * @param {string} language - Language code (ISO 639-1)
 * @returns {Object} Translations
 */
export const getTranslations = (language) => {
  // Get language specific translations or default to English
  const langTranslations = translations[language] || translations.en;

  // Ensure all keys from default translations exist
  const result = { ...defaultTranslations, ...langTranslations };

  return result;
};

// Default translations for each language
export const languageTranslations = {
  hi: {
    title: "हस्ताक्षर के लिए प्रतीक्षारत दस्तावेज़",
    welcome: "नमस्ते",
    description:
      "आपके हस्ताक्षर के लिए दस्तावेज़ प्रतीक्षार हैं। कृपया उन्हें देखे और हस्ताक्षर करें।",
    status: { signed: "हस्ताक्षरित", waiting: "हस्ताक्षर की प्रतीक्षा में" },
    signButton: "दस्तावेज़ पर हस्ताक्षर करें",
    loading: "लोड हो रहा है...",
    noDocuments: "हस्ताक्षर के लिए कोई दस्तावेज़ नहीं",
    createdAt: "बनाया गया:",
    // Sign-in translations
    verifyAccount: "अपने खाते को सत्यापित करें",
    enterPassword:
      "इस दस्तावेज़ को देखने के लिए कृपया एसएमएस में मिली पासवर्ड दर्ज करें।",
    submit: "प्रस्तुत",
    password: "पासवर्ड",
    // Signature translations
    clearSignature: "हस्ताक्षर साफ़ करें",
    signAllFields: "सभी क्षेत्रों पर हस्ताक्षर करें",
    saveAndNext: "सहेजें और अगला",
    signAndFinish: "हस्ताक्षर करें और समाप्त करें",
    quickSignature: "त्वरित हस्ताक्षर",
    selectSignatureField: "हस्ताक्षर क्षेत्र चुनें",
    signaturesCompleted: "हस्ताक्षर पूर्ण",
    outOf: "में से",
    page: "पृष्ठ",
    movingToPage: "पृष्ठ पर जा रहा है",
    allSignaturesCompleted: "सभी हस्ताक्षर पूर्ण हो गए हैं",
    signature: "हस्ताक्षर",
    // PDF form translations
    save: "सहेजें",
    saving: "सहेज रहा है...",
    saveAndNext: "सहेजें और अगला",
    moveToNextDoc: "सहेजें और अगले दस्तावेज़ पर जाएं",
    current: "(वर्तमान)",
    pleaseSignBelow: "कृपया नीचे हस्ताक्षर करें",
    requiredSignature: "हस्ताक्षर आवश्यक है पृष्ठ",
    movingToNextDoc: "अगले दस्तावेज़ पर जा रहा है...",
    formSavedSuccess: "फ़ॉर्म सफलतापूर्वक सहेजा गया",
    noSignaturesFound: "हस्ताक्षर नहीं मिले",
    noSignaturesDescription: "कृपया अपने दस्तावेज़ को देखें और हस्ताक्षर करें।",
    noSignaturesFound: "हस्ताक्षर नहीं मिले",
    errorSavingForm: "फ़ॉर्म सहेजने में त्रुटि",
    quickFillForm: "त्वरित भरें फॉर्म",
    complete: "पूर्ण",
    next: "अगला",
    back: "पीछे",
    clearAll: "सभी साफ़ करें",
    invalidCode: "अमान्य कोड। कृपया पुनः प्रयास करें।",
    tryAgainIn: "में पुनः प्रयास करें",
    seconds: "सेकंड",
    codeSent: "नया कोड भेज दिया गया है",
    resendCode: "कोड पुनः भेजें",
    error: "कुछ गलत हो गया। कृपया पुनः प्रयास करें।",
    // Worker Details
    passport: "पासपोर्ट नंबर",
    // Clock Actions
    clockIn: "क्लॉक इन",
    clockOut: "क्लॉक आउट",
    pause: "विराम",
    resume: "जारी रखें",
    submitRequest: "अनुरोध जमा करें",
    // Navigation
    monthlyReport: "मासिक रिपोर्ट",
    mySalarySlips: "मेरी वेतन पर्ची",
    signHoursReport: "घंटों की रिपोर्ट पर हस्ताक्षर करें",
    // Working Hours
    noRecordsFound: "इस महीने के लिए कोई रिकॉर्ड नहीं मिला",
    // Months
    months: {
      january: "जनवरी",
      february: "फरवरी",
      march: "मार्च",
      april: "अप्रैल",
      may: "मई",
      june: "जून",
      july: "जुलाई",
      august: "अगस्त",
      september: "सितंबर",
      october: "अक्टूबर",
      november: "नवंबर",
      december: "दिसंबर",
    },
    // GPS Messages
    gpsRequired: "स्थान की आवश्यकता है",
    gpsError: "स्थान प्राप्त करने में त्रुटि",
    // Request Modal
    requestTitle: "अनुरोध प्रकार चुनें",
    requestTypes: {
      timeChange: "समय परिवर्तन",
      timeChangeDesc: "मैनुअल समय रिपोर्टिंग",
      sickLeave: "बीमारी की छुट्टी",
      sickLeaveDesc: "बीमारी के दिन की रिपोर्ट",
      dayOff: "छुट्टी का दिन",
      dayOffDesc: "छुट्टी के दिन की रिपोर्ट",
      holiday: "छुट्टी",
      holidayDesc: "छुट्टी के दिन की रिपोर्ट",
      other: "अन्य",
    },
    attendance: "उपस्थिति",
    // Location Messages
    browserNotSupported: "आपका ब्राउ़़र GPS स्थान का समर्थन नहीं करता है",
    locationUnavailable:
      "GPS स्थान अभी उपलब्ध नहीं है, कृपया कुछ सेकंड में पुनः प्रयास करें",
    locationPermissionDenied:
      "उपस्थिति दर्ज करने के लिए GPS स्थान की अनुमति आवश्यक है",
    locationTimeout:
      "GPS स्थान प्राप्त करने का समय समाप्त हो गया, कृपया पुनः प्रयास करें",
    locationError: "GPS स्थान प्राप्त करने में त्रुटि, कृपया पुनः प्रयास करें",
    approve: "स्वीकृत करें",
    edit: "संपादित करें",
    minutes: "मिनट",
    hours: "घंटे",
    notesPlaceholder: "कृपया अनुरोध का कारण विस्तार से बताएं...",
    close: "बंद करें",
    // Location Settings
    locationRequired: "स्थान पहुंच आवश्यक है",
    locationInstructions:
      "पंच इन/आउट करने के लिए, हमें आपके स्थान तक पहुंच की आवश्यकता है। कृपया इन चरणों का पालन करें:",
    howToEnable: "स्थान कैसे सक्षम करें:",
    step1: "डिवाइस सेटिंग्स खोलें",
    step2: "गोपनीयता और सुरक्षा पर जाएं",
    step3: "स्थान सेवाएं चुनें",
    step4: "इस ऐप के लिए स्थान सक्षम करें",
    openSettings: "सेटिंग्स खोलें",
    locationNotAvailable: "स्थान उपलब्ध नहीं है",
    openLocationSettings: "स्थान सेटिंग्स खोलें",
    cancel: "रद्द करें",
    // Notification translations
    clockInSuccess: "पंच इन सफल",
    clockOutSuccess: "पंच आउट सफल",
    clockInReminder: "पंच इन का समय",
    clockOutReminder: "पंच आउट का समय",
    locationPermissionDeniedDesc:
      "कृपया पंच इन/आउट के लिए स्थान सेवाएं सक्षम करें",
    locationUnavailableDesc: "कृपया कुछ क्षणों में पुनः प्रयास करें",
    notificationTitle: "कार्य समय अधिसूचना",
    timeToClockIn: "पंच इन का समय हो गया है",
    timeToClockOut: "पंच आउट का समय हो गया है",
    // Permissions Modal
    permissionsRequired: "अनुमतियां आवश्यक हैं",
    permissionsDescription:
      "सर्वोत्तम अनुभव प्रदान करने के लिए, हमें आपकी अनुमति की आवश्यकता है:",
    locationPermissionTitle: "स्थान पहुंच",
    locationPermissionDesc: "आपकी उपस्थिति को सटीक रूप से दर्ज करने के लिए",
    notificationPermissionTitle: "पुश सूचनाएं",
    notificationPermissionDesc:
      "क्लॉक इन/आउट समय के बारे में याद दिलाने के लिए",
    later: "बाद में",
    unknownLocation: "अज्ञात स्थान",
    logout: "लॉग आउट",
    logoutConfirmation: "क्या आप लॉग आउट करना चाहते हैं?",
    confirm: "पुष्टि करें",
    cancel: "रद्द करें",
    logoutError: "लॉग आउट करने में त्रुटि",
    // Worker Daily Summary
    invalidSession: "सत्र अमान्य है!",
    workerNotFound: "कर्मचारी नहीं मिला!",
    somethingWentWrong: "कुछ गलत हो गया!",
    notWorkingDay: "यह कार्य दिवस नहीं है!",
    // Comment Tags
    commentTags: {
      notWorkingDay: "यह कार्य दिवस नहीं है",
      alreadyClockedOut: "पहले से ही क्लॉक आउट किया गया है",
      beyondSiteHours: "साइट के कार्य समय से बाहर",
      exceededDailyHours: "दैनिक कार्य घंटे पार हो गए हैं",
      didntClockOutAction: "क्लॉक आउट करना भूल गए?",
    },
    // File Upload translations
    attachments: "संलग्न फ़ाइलें",
    uploadFile: "फ़ाइल अपलोड करें",
    takePhoto: "फोटो लें",
    noFilesYet: "अभी तक कोई फ़ाइल अपलोड नहीं की गई",
    notes: "टिप्पणियाँ",
    // Request History Page
    requestHistory: "अनुरोध की इतिहास",
    requestHistoryDesc: "आपने अनुरोध की विस्तृत जानकारी देखी है",
    backToHome: "घर पर वापस जाएं",
    noRequests: "अनुरोध नहीं है",
    newRequestsWillAppear: "नए अनुरोध यहाँ दिखाई देंगे",
    filterByDate: "तारीख के अनुसार फ़िल्टर",
    startDate: "शुरुआत की तारीख",
    endDate: "समाप्ति की तारीख",
    applyFilter: "फ़िल्टर लगाएं",
    clearFilter: "फ़िल्टर साफ़ करें",
    createdOn: "निर्मित हुआ:",
    updatedOn: "अद्यतन हुआ:",
    handledBy: "इस कार्य को किसने किया",
    enterStartTime: "इन्स्टार्ट टाइम",
    exitTime: "आउट टाइम",
    // Request statuses
    approved: "अनुमोदन करें",
    rejected: "अस्वीकृत करें",
    pending: "प्रतीक्षा में",
    // Request types
    requestTypes: {
      timeChange: "समय परिवर्तन",
      timeChangeDesc: "मैनुअल समय रिपोर्टिंग",
      sickLeave: "बीमारी की छुट्टी",
      sickLeaveDesc: "बीमारी के दिन की रिपोर्ट",
      dayOff: "छुट्टी का दिन",
      dayOffDesc: "छुट्टी के दिन की रिपोर्ट",
      holiday: "छुट्टी",
      holidayDesc: "छुट्टी के दिन की रिपोर्ट",
      other: "अन्य",
      overtime: "अतिरिक्त समय",
    },
  },
  ro: {
    title: "Documente în așteptarea semnăturii",
    welcome: "Bună ziua",
    description:
      "Aveți documente în așteptarea semnăturii. Vă rugăm să le revizuiți și să le semnați.",
    status: { signed: "Semnat", waiting: "În așteptarea semnăturii" },
    signButton: "Semnați documentul",
    loading: "Se încarcă...",
    noDocuments: "Nu există documente de semnat",
    createdAt: "Creat la:",
    // Sign-in translations
    verifyAccount: "Verificați-vă contul",
    enterPassword:
      "Vă rugăm să introduceți parola primită prin SMS pentru a vizualiza acest document.",
    submit: "Trimite",
    password: "Parolă",
    // Signature translations
    clearSignature: "Șterge semnătura",
    noSignaturesFound: "Nu există semnături",
    noSignaturesDescription: "Vă rugăm să verificați documentul și să semnați.",
    signAndFinishClose: "Șterge",
    signAllFields: "Semnează toate câmpurile",
    saveAndNext: "Salvează și următorul",
    signAndFinish: "Semnează și finalizează",
    quickSignature: "Semnătură rapidă",
    selectSignatureField: "Selectează câmpul de semnătură",
    signaturesCompleted: "Semnături completate",
    outOf: "din",
    page: "Pagina",
    movingToPage: "Se mută la pagina",
    allSignaturesCompleted: "Toate semnăturile au fost completate",
    signature: "Semnătură",
    // PDF form translations
    save: "Salvează",
    saving: "Se salvează...",
    saveAndNext: "Salvează și următorul",
    moveToNextDoc: "Salvează și treci la următorul document",
    current: "(curent)",
    pleaseSignBelow: "Vă rugăm să semnați mai jos",
    requiredSignature: "Semnătură necesară pe pagina",
    movingToNextDoc: "Se trece la următorul document...",
    formSavedSuccess: "Formularul a fost salvat cu succes",
    errorSavingForm: "Eroare la salvarea formularului",
    quickFillForm: "Completare rapidă formular",
    complete: "Finalizează",
    next: "Următorul",
    back: "Înapoi",
    clearAll: "Șterge tot",
    invalidCode: "Cod invalid. Vă rugăm să încercați din nou.",
    tryAgainIn: "Încercați din nou în",
    seconds: "secunde",
    codeSent: "Un nou cod a fost trimis",
    resendCode: "Retrimite codul",
    error: "Ceva n-a mers bine. Vă rugăm să încercați din nou.",
    // Worker Details
    passport: "Număr Pașaport",
    // Clock Actions
    clockIn: "Pontare Intrare",
    clockOut: "Pontare Ieșire",
    pause: "Pauză",
    resume: "Continuă",
    submitRequest: "Trimite Cerere",
    // Navigation
    monthlyReport: "Raport Lunar",
    mySalarySlips: "Fluturașii mei de salariu",
    signHoursReport: "Semnează Raportul de Ore",
    // Working Hours
    noRecordsFound: "Nu s-au găsit înregistrări pentru această lună",
    // Months
    months: {
      january: "Ianuarie",
      february: "Februarie",
      march: "Martie",
      april: "Aprilie",
      may: "Mai",
      june: "Iunie",
      july: "Iulie",
      august: "August",
      september: "Septembrie",
      october: "Octombrie",
      november: "Noiembrie",
      december: "Decembrie",
    },
    // GPS Messages
    gpsRequired: "Locația este necesară",
    gpsError: "Eroare la obținerea locației",
    // Request Modal
    requestTitle: "Selectați Tipul Cererii",
    requestTypes: {
      timeChange: "Modificare Timp",
      timeChangeDesc: "Raportare manuală a timpului",
      sickLeave: "Concediu Medical",
      sickLeaveDesc: "Raportare zi de boală",
      dayOff: "Zi Liberă",
      dayOffDesc: "Raportare zi liberă",
      holiday: "Sărbătoare",
      holidayDesc: "Raportare zi de sărbătoare",
      other: "Altele",
    },
    attendance: "Prezență",
    // Location Messages
    browserNotSupported: "Browserul dvs. nu suportă localizare GPS",
    locationUnavailable:
      "Locația GPS nu este disponibilă momentan, încercați din nou în câteva secunde",
    locationPermissionDenied:
      "Permisiunea de localizare GPS este necesară pentru pontaj",
    locationTimeout:
      "Timpul pentru obținerea locației GPS a expirat, încercați din nou",
    locationError: "Eroare la obținerea locației GPS, încercați din nou",
    approve: "Aprobă",
    edit: "Editează",
    minutes: "min",
    hours: "ore",
    notesPlaceholder: "Vă rugăm să detaliați motivul cererii...",
    close: "Închide",
    // Location Settings
    locationRequired: "Acces la locație necesar",
    locationInstructions:
      "Pentru a putea înregistra prezența, avem nevoie de acces la locația dvs. Vă rugăm să urmați acești pași:",
    howToEnable: "Cum să activați locația:",
    step1: "Deschideți setările dispozitivului",
    step2: "Mergeți la Confidențialitate și Securitate",
    step3: "Selectați Servicii de localizare",
    step4: "Activați locația pentru această aplicație",
    openSettings: "Deschide Setări",
    locationNotAvailable: "Locație indisponibilă",
    openLocationSettings: "Deschide Setări Locație",
    cancel: "Anulare",
    // Notification translations
    clockInSuccess: "Pontare Intrare Reușită",
    clockOutSuccess: "Pontare Ieșire Reușită",
    clockInReminder: "Reamintire Pontare Intrare",
    clockOutReminder: "Reamintire Pontare Ieșire",
    locationPermissionDeniedDesc:
      "Vă rugăm să activați serviciile de localizare pentru pontaj",
    locationUnavailableDesc: "Vă rugăm să încercați din nou în câteva momente",
    notificationTitle: "Notificare Timp de Lucru",
    timeToClockIn: "Este timpul să pontați intrarea",
    timeToClockOut: "Este timpul să pontați ieșirea",
    // Permissions Modal
    permissionsRequired: "Permisiuni necesare",
    permissionsDescription:
      "Pentru a vă oferi cea mai bună experiență, avem nevoie de permisiunea dvs. pentru:",
    locationPermissionTitle: "Acces la locație",
    locationPermissionDesc: "Pentru a înregistra cu precizie prezența dvs.",
    notificationPermissionTitle: "Notificări push",
    notificationPermissionDesc: "Pentru a vă reaminti despre orele de pontaj",
    later: "Mai târziu",
    unknownLocation: "Locație necunoscută",
    logout: "Deconectare",
    logoutConfirmation: "Sigur doriți să vă deconectați?",
    confirm: "Confirmă",
    cancel: "Anulare",
    logoutError: "Eroare la deconectare",
    // Worker Daily Summary
    invalidSession: "Sesiune invalidă!",
    workerNotFound: "Muncitorul nu a fost găsit!",
    somethingWentWrong: "Ceva nu a mers bine!",
    notWorkingDay: "Nu este o zi lucrătoare!",
    // Comment Tags
    commentTags: {
      notWorkingDay: "Nu este o zi lucrătoare",
      alreadyClockedOut: "Deja ați ieșit",
      beyondSiteHours: "În afara orelor de lucru ale șantierului",
      exceededDailyHours: "Ați depășit orele zilnice de lucru",
      didntClockOutAction: "Ați uitat să ieșiți?",
    },
    // File Upload translations
    attachments: "Atașamente",
    uploadFile: "Încarcă fișier",
    takePhoto: "Fă o poză",
    noFilesYet: "Niciun fișier încărcat încă",
    notes: "Note",
    // Request History Page
    requestHistory: "Istoria cererilor",
    requestHistoryDesc: "Vedeți toate cererile trimise și stările lor",
    backToHome: "Întoarcere la pagina principală",
    noRequests: "Nu există cereri",
    newRequestsWillAppear: "Noi cereri vor apărea aici",
    filterByDate: "Filtrare după dată",
    startDate: "Data începerii",
    endDate: "Data încheierii",
    applyFilter: "Aplică filtrare",
    clearFilter: "Șterge filtrarea",
    createdOn: "Creat la:",
    updatedOn: "Actualizat la:",
    handledBy: "Tratat de",
    enterStartTime: "Intrare",
    exitTime: "Ieșire",
    // Request statuses
    approved: "Aprobă",
    rejected: "Respins",
    pending: "În așteptarea aprobării",
    // Request types
    requestTypes: {
      timeChange: "Modificare Timp",
      timeChangeDesc: "Raportare manuală a timpului",
      sickLeave: "Concediu Medical",
      sickLeaveDesc: "Raportare zi de boală",
      dayOff: "Zi Liberă",
      dayOffDesc: "Raportare zi liberă",
      holiday: "Sărbătoare",
      holidayDesc: "Raportare zi de sărbătoare",
      other: "Altele",
      overtime: "Ore suplimentare",
    },
  },
  he: {
    title: "מסמכים הממתינים לחתימה",
    welcome: "שלום",
    description: "יש לך מסמכים הממתינים לחתימה. אנא עבור עליהם וחתום.",
    status: { signed: "חתום", waiting: "ממתין לחתימה" },
    signButton: "חתום על המסמך",
    loading: "טוען...",
    noDocuments: "אין מסמכים לחתימה",
    noSignaturesFound: "אין חתימות",
    noSignaturesDescription: "אנא בדוק את המסמך וחתום.",
    createdAt: "נוצר ב:",
    // Sign-in translations
    verifyAccount: "אימות חשבון",
    enterPassword: "אנא הכנס את הקוד שנשלח אליך",
    password: "קוד",
    submit: "שלח",
    invalidCode: "קוד לא תקין",
    tryAgainIn: "נסה שוב בעוד",
    seconds: "שניות",
    resendCode: "שלח קוד חדש",
    codeSent: "קוד חדש נשלח",
    error: "שגיאה",

    // Signature translations
    clearSignature: "נקה חתימה",
    signAllFields: "חתום בכל השדות",
    saveAndNext: "שמור וחתום הבא",
    signAndFinish: "חתום וסיים",
    signAndFinishClose: "סגור",
    quickSignature: "חתימה מהירה",
    selectSignatureField: "בחר שדה חתימה",
    signaturesCompleted: "חתימות הושלמו",
    outOf: "מתוך",
    page: "עמוד",
    movingToPage: "עובר לעמוד",
    allSignaturesCompleted: "כל החתימות הושלמו",
    signature: "חתימה",

    // PDF form translations
    save: "שמירה",
    saving: "שומר...",
    saveSignature: "שמור חתימה",
    signHere: "חתום כאן",
    moveToNextDoc: "שמור ועבור למסמך הבא",
    current: "(נוכחי)",
    pleaseSignBelow: "אנא חתום למטה",
    requiredSignature: "נדרשת חתימה בעמוד",
    movingToNextDoc: "עובר למסמך הבא...",
    formSavedSuccess: "הטופס נשמר בהצלחה",
    errorSavingForm: "שגיאה בשמירת הטופס",
    quickFillForm: "מילוי מהיר",
    complete: "סיום",
    next: "הבא",
    back: "חזור",
    clearAll: "נקה הכל",
    close: "סגור",
    cancel: "בטל",
    confirm: "אשר",
    done: "סיום",
    // Worker Details
    passport: "מספר דרכון",
    // Clock Actions
    clockIn: "כניסה",
    clockOut: "יציאה",
    pause: "עצירה זמנית",
    resume: "המשך עבודה",
    submitRequest: "הגש בקשה",
    // Navigation
    monthlyReport: "מעבר לדיווח החודשי",
    mySalarySlips: "תלושי השכר שלי",
    signHoursReport: "חתימה על דוח שעות",
    // Working Hours
    noRecordsFound: "לא נמצאו רשומות לחודש זה",
    // Months
    months: {
      january: "ינואר",
      february: "פברואר",
      march: "מרץ",
      april: "אפריל",
      may: "מאי",
      june: "יוני",
      july: "יולי",
      august: "אוגוסט",
      september: "ספטמבר",
      october: "אוקטובר",
      november: "נובמבר",
      december: "דצמבר",
    },
    // GPS Messages
    gpsRequired: "נדרש מיקום GPS לדיווח נוכחות",
    gpsError: "שגיאה בקבלת מיקום",
    // Request Modal
    requestTitle: "בחר סוג בקשה",
    requestTypes: {
      timeChange: "שינוי שעות",
      timeChangeDesc: "דיווח ידני על שעות עבודה",
      sickLeave: "מחלה",
      sickLeaveDesc: "דיווח על יום מחלה",
      dayOff: "יום חופש",
      dayOffDesc: "דיווח על יום חופשה",
      holiday: "חג",
      holidayDesc: "דיווח על יום חג",
      other: "אחר",
    },
    attendance: "נוכחות",
    // Location Messages
    browserNotSupported: "הדפדפן שלך לא תומך במיקום GPS",
    locationUnavailable: "לא ניתן לקבל מיקום GPS כרגע, נסה שוב בעוד מספר שניות",
    locationPermissionDenied: "יש לאפשר גישה למיקום GPS כדי לדווח נוכחות",
    locationTimeout: "תם הזמן לקבלת מיקום GPS, נסה שוב",
    locationError: "שגיאה בקבלת מיקום GPS, נסה שוב",
    approve: "אישור",
    edit: "שינוי",
    minutes: "דק׳",
    hours: "שע׳",
    notesPlaceholder: "נא לפרט את סיבת הדיווח...",
    close: "סגור",
    // Location Settings
    locationRequired: "נדרשת גישה למיקום",
    locationInstructions:
      "כדי לדווח נוכחות, אנחנו צריכים גישה למיקום שלך. אנא עקוב אחר השלבים הבאים:",
    howToEnable: "כיצד להפעיל מיקום:",
    step1: "פתח הגדרות מכשיר",
    step2: "עבור לפרטיות ואבטחה",
    step3: "בחר שירותי מיקום",
    step4: "הפעל מיקום עבור אפליקציה זו",
    openSettings: "פתח הגדרות",
    locationNotAvailable: "מיקום לא זמין",
    openLocationSettings: "פתח הגדרות מיקום",
    cancel: "ביטול",
    // Notification translations
    clockInSuccess: "כניסה נרשמה בהצלחה",
    clockOutSuccess: "יציאה נרשמה בהצלחה",
    clockInReminder: "תזכורת לרישום כניסה",
    clockOutReminder: "תזכורת לרישום יציאה",
    locationPermissionDeniedDesc: "יש לאפשר שירותי מיקום לצורך דיווח נוכחות",
    locationUnavailableDesc: "אנא נסה שוב בעוד מספר רגעים",
    notificationTitle: "התראת שעות עבודה",
    timeToClockIn: "הגיע הזמן לרשום כניסה",
    timeToClockOut: "הגיע הזמן לרשום יציאה",
    // Permissions Modal
    permissionsRequired: "נדרשות הרשאות",
    permissionsDescription:
      "כדי לספק לך את החוויה הטובה ביותר, אנחנו צריכים את אישורך עבור:",
    locationPermissionTitle: "גישה למיקום",
    locationPermissionDesc: "כדי לתעד את הנוכחות שלך במדויק",
    notificationPermissionTitle: "התראות",
    notificationPermissionDesc: "כדי להזכיר לך על זמני כניסה/יציאה",
    later: "אחר כך",
    unknownLocation: "מיקום לא ידוע",
    logout: "התנתק",
    logoutConfirmation: "האם אתה בטוח שברצונך להתנתק?",
    confirm: "אישור",
    cancel: "ביטול",
    logoutError: "שגיאה בהתנתקות",
    // Worker Daily Summary
    invalidSession: "!סשן לא תקין",
    workerNotFound: "!העובד לא נמצא",
    somethingWentWrong: "!משהו השתבש",
    notWorkingDay: "!היום אינו יום עבודה",
    // Comment Tags
    commentTags: {
      notWorkingDay: "היום אינו יום עבודה",
      alreadyClockedOut: "כבר ביצעת יציאה",
      beyondSiteHours: "מחוץ לשעות העבודה באתר",
      exceededDailyHours: "חרגת משעות העבודה היומיות",
      didntClockOutAction: "שכחת לבצע יציאה?",
    },
    // File Upload translations
    attachments: "קבצים מצורפים",
    uploadFile: "העלה קובץ",
    takePhoto: "צלם תמונה",
    noFilesYet: "טרם הועלו קבצים",
    notes: "הערות",
    // Request History Page
    requestHistory: "היסטוריית בקשות",
    requestHistoryDesc: "צפה בכל הבקשות שהגשת ובסטטוס שלהן",
    backToHome: "חזרה לדף הבית",
    noRequests: "אין בקשות",
    newRequestsWillAppear: "בקשות חדשות שתגיש יופיעו כאן",
    filterByDate: "סנן לפי תאריך",
    startDate: "תאריך התחלה",
    endDate: "תאריך סיום",
    applyFilter: "החל סינון",
    clearFilter: "נקה סינון",
    createdOn: "נוצר ב-",
    updatedOn: "עודכן ב-",
    handledBy: "טופל על ידי",
    enterStartTime: "כניסה",
    exitTime: "יציאה",
    // Request statuses
    approved: "אושר",
    rejected: "נדחה",
    pending: "ממתין לאישור",
    // Request types
    requestTypes: {
      timeChange: "תיקון שעון",
      timeChangeDesc: "דיווח זמן ידני",
      sickLeave: "מחלה",
      sickLeaveDesc: "דיווח יום מחלה",
      dayOff: "יום חופש",
      dayOffDesc: "דיווח יום חופש",
      holiday: "חג",
      holidayDesc: "דיווח יום חג",
      other: "סיבה אישית",
      overtime: "שעות נוספות",
    },
  },
  zh: {
    title: "等待签名的文件",
    welcome: "您好",
    description: "您有待签名的文件。请查看并签名。",
    status: { signed: "已签名", waiting: "等待签名" },
    signButton: "签署文件",
    loading: "加载中...",
    noDocuments: "没有需要签名的文件",
    createdAt: "创建于:",
    // Sign-in translations
    verifyAccount: "验证您的帐户",
    enterPassword: "请输入短信中收到的密码以查看此文档。",
    submit: "提交",
    password: "密码",
    // Signature translations
    clearSignature: "清除签名",
    signAllFields: "签署所有字段",
    saveAndNext: "保存并继续",
    signAndFinish: "签署并完成",
    noSignaturesFound: "没有签名",
    noSignaturesDescription: "请查看文档并签名。",
    signAndFinishClose: "关闭",

    quickSignature: "快速签名",
    selectSignatureField: "选择签名字段",
    signaturesCompleted: "签名完成",
    outOf: "之",
    page: "页",
    movingToPage: "正在移至页面",
    allSignaturesCompleted: "所有签名已完成",
    signature: "签名",
    // PDF form translations
    save: "保存",
    saving: "保存中...",
    saveAndNext: "保存并继续",
    moveToNextDoc: "保存并转到下一个文档",
    current: "(当前)",
    pleaseSignBelow: "请在下方签名",
    requiredSignature: "需要在页面签名",
    movingToNextDoc: "正在转到下一个文档...",
    formSavedSuccess: "表单保存成功",
    errorSavingForm: "保存表单时出错",
    quickFillForm: "快速填写表单",
    complete: "完成",
    next: "下一步",
    back: "返回",
    clearAll: "清除全部",
    invalidCode: "验证码无效。请重试。",
    tryAgainIn: "请在以下时间后重试",
    seconds: "秒",
    codeSent: "新验证码已发送",
    resendCode: "重新发送验证码",
    error: "出现错误。请重试。",
    // Worker Details
    passport: "护照号码",
    // Clock Actions
    clockIn: "上班打卡",
    clockOut: "下班打卡",
    pause: "暂停",
    resume: "继续",
    submitRequest: "提交申请",
    // Navigation
    monthlyReport: "月度报告",
    mySalarySlips: "我的工资单",
    signHoursReport: "签署工时报告",
    // Working Hours
    noRecordsFound: "本月没有记录",
    // Months
    months: {
      january: "一月",
      february: "二月",
      march: "三月",
      april: "四月",
      may: "五月",
      june: "六月",
      july: "七月",
      august: "八月",
      september: "九月",
      october: "十月",
      november: "十一月",
      december: "十二月",
    },
    // GPS Messages
    gpsRequired: "需要位置信息",
    gpsError: "获取位置时出错",
    // Request Modal
    requestTitle: "选择申请类型",
    requestTypes: {
      timeChange: "时间变更",
      timeChangeDesc: "手动时间报告",
      sickLeave: "病假",
      sickLeaveDesc: "病假日报告",
      dayOff: "休假",
      dayOffDesc: "休假日报告",
      holiday: "节假日",
      holidayDesc: "节假日报告",
      other: "其他",
    },
    attendance: "考勤",
    // Location Messages
    browserNotSupported: "您的浏览器不支持GPS定位",
    locationUnavailable: "当前无法获取GPS位置，请稍后重试",
    locationPermissionDenied: "需要GPS位置权限才能打卡",
    locationTimeout: "GPS位置获取超时，请重试",
    locationError: "获取GPS位置时出错，请重试",
    approve: "批准",
    edit: "编辑",
    minutes: "分钟",
    hours: "小时",
    notesPlaceholder: "请详细说明申请原因...",
    close: "关闭",
    // Notification translations
    clockInSuccess: "打卡成功",
    clockOutSuccess: "下班打卡成功",
    clockInReminder: "上班打卡提醒",
    clockOutReminder: "下班打卡提醒",
    locationPermissionDeniedDesc: "请启用位置服务以进行打卡",
    locationUnavailableDesc: "请稍后重试",
    notificationTitle: "工作时间通知",
    timeToClockIn: "该上班打卡了",
    timeToClockOut: "该下班打卡了",
    // Permissions Modal
    permissionsRequired: "需要权限",
    permissionsDescription: "为了给您提供最佳体验，我们需要您的以下权限：",
    locationPermissionTitle: "位置访问",
    locationPermissionDesc: "准确记录您的考勤",
    notificationPermissionTitle: "推送通知",
    notificationPermissionDesc: "提醒您打卡时间",
    later: "稍后",
    unknownLocation: "未知位置",
    logout: "退出登录",
    logoutConfirmation: "确定要退出登录吗？",
    confirm: "确认",
    cancel: "取消",
    logoutError: "退出登录时出错",
    // Worker Daily Summary
    invalidSession: "会话无效！",
    workerNotFound: "未找到工人！",
    somethingWentWrong: "出现错误！",
    notWorkingDay: "今天不是工作日！",
    // Comment Tags
    commentTags: {
      notWorkingDay: "今天不是工作日",
      alreadyClockedOut: "已经打卡下班",
      beyondSiteHours: "超出工地工作时间",
      exceededDailyHours: "超出每日工作时间",
      didntClockOutAction: "忘记打卡下班？",
    },
    // File Upload translations
    attachments: "附件",
    uploadFile: "上传文件",
    takePhoto: "拍照",
    noFilesYet: "尚未上传文件",
    notes: "备注",
    // Request History Page
    requestHistory: "请求历史",
    requestHistoryDesc: "查看所有提交的请求及其状态",
    backToHome: "返回首页",
    noRequests: "没有请求",
    newRequestsWillAppear: "新请求将在这里出现",
    filterByDate: "按日期筛选",
    startDate: "开始日期",
    endDate: "结束日期",
    applyFilter: "应用筛选",
    clearFilter: "清除筛选",
    createdOn: "创建于:",
    updatedOn: "更新于:",
    handledBy: "由",
    enterStartTime: "进入时间",
    exitTime: "退出时间",
    // Request statuses
    approved: "已批准",
    rejected: "已拒绝",
    pending: "等待批准",
    // Request types
    requestTypes: {
      timeChange: "时间变更",
      timeChangeDesc: "手动时间报告",
      sickLeave: "病假",
      sickLeaveDesc: "病假日报告",
      dayOff: "休假",
      dayOffDesc: "休假日报告",
      holiday: "节假日",
      holidayDesc: "节假日报告",
      other: "其他",
    },
  },
  en: {
    title: "Documents Awaiting Signature",
    welcome: "Hello",
    description:
      "You have documents awaiting signature. Please review and sign them.",
    status: { signed: "Signed", waiting: "Awaiting Signature" },
    signButton: "Sign Document",
    loading: "Loading...",
    noDocuments: "No documents to sign",
    createdAt: "Created at:",
    // Sign-in translations
    verifyAccount: "Verify Your Account",
    enterPassword:
      "Please enter the password received in SMS to view this document.",
    submit: "Submit",
    password: "Password",
    // Signature translations
    clearSignature: "Clear Signature",
    signAllFields: "Sign All Fields",
    saveAndNext: "Save & Next",
    noSignaturesFound: "No signatures found",
    noSignaturesDescription: "Please review the document and sign.",
    signAndFinish: "Sign & Finish",
    signAndFinishClose: "Close",
    quickSignature: "Quick Signature",
    selectSignatureField: "Select Signature Field",
    signaturesCompleted: "Signatures Completed",
    outOf: "out of",
    page: "Page",
    movingToPage: "Moving to page",
    allSignaturesCompleted: "All signatures completed",
    signature: "Signature",
    // PDF form translations
    save: "Save",
    saving: "Saving...",
    saveAndNext: "Save & Next",
    moveToNextDoc: "Save & Move to Next Document",
    current: "(current)",
    pleaseSignBelow: "Please sign below",
    requiredSignature: "Signature required on page",
    movingToNextDoc: "Moving to next document...",
    formSavedSuccess: "Form saved successfully",
    errorSavingForm: "Error saving form",
    quickFillForm: "Quick Fill Form",
    complete: "Complete",
    next: "Next",
    back: "Back",
    clearAll: "Clear All",
    invalidCode: "Invalid code. Please try again.",
    tryAgainIn: "Try again in",
    seconds: "seconds",
    codeSent: "New code has been sent",
    resendCode: "Resend Code",
    error: "Something went wrong. Please try again.",
    // Worker Details
    passport: "Passport Number",
    // Clock Actions
    clockIn: "Clock In",
    clockOut: "Clock Out",
    pause: "Pause",
    resume: "Resume",
    submitRequest: "Submit Request",
    // Navigation
    monthlyReport: "Monthly Report",
    mySalarySlips: "My Salary Slips",
    signHoursReport: "Sign Hours Report",
    // Working Hours
    noRecordsFound: "No records found for this month",
    // Months
    months: {
      january: "January",
      february: "February",
      march: "March",
      april: "April",
      may: "May",
      june: "June",
      july: "July",
      august: "August",
      september: "September",
      october: "October",
      november: "November",
      december: "December",
    },
    // GPS Messages
    gpsRequired: "Location is required",
    gpsError: "Error getting location",
    // Request Modal
    requestTitle: "Select Request Type",
    requestTypes: {
      timeChange: "Time Change",
      timeChangeDesc: "Manual time reporting",
      sickLeave: "Sick Leave",
      sickLeaveDesc: "Report sick day",
      dayOff: "Day Off",
      dayOffDesc: "Report vacation day",
      holiday: "Holiday",
      holidayDesc: "Report holiday",
      other: "Other",
    },
    attendance: "Attendance",
    // Location Messages
    browserNotSupported: "Your browser does not support GPS location",
    locationUnavailable:
      "GPS location is currently unavailable, please try again in a few seconds",
    locationPermissionDenied:
      "GPS location permission is required for attendance",
    locationTimeout: "GPS location request timed out, please try again",
    locationError: "Error getting GPS location, please try again",
    approve: "Approve",
    edit: "Edit",
    minutes: "min",
    hours: "hrs",
    notesPlaceholder: "Please detail the reason for the request...",
    close: "Close",
    // Notification translations
    clockInSuccess: "Clock In Successful",
    clockOutSuccess: "Clock Out Successful",
    clockInReminder: "Clock In Reminder",
    clockOutReminder: "Clock Out Reminder",
    locationPermissionDeniedDesc:
      "Please enable location services to clock in/out",
    locationUnavailableDesc: "Please try again in a few moments",
    notificationTitle: "Work Time Notification",
    timeToClockIn: "Time to clock in",
    timeToClockOut: "Time to clock out",
    // Permissions Modal
    permissionsRequired: "Permissions Required",
    permissionsDescription:
      "To provide you with the best experience, we need your permission for:",
    locationPermissionTitle: "Location Access",
    locationPermissionDesc: "To accurately record your attendance",
    notificationPermissionTitle: "Push Notifications",
    notificationPermissionDesc: "To remind you about clock in/out times",
    later: "Later",
    unknownLocation: "Unknown Location",
    logout: "Logout",
    logoutConfirmation: "Are you sure you want to logout?",
    confirm: "Confirm",
    cancel: "Cancel",
    logoutError: "Error logging out",
    // Worker Daily Summary
    invalidSession: "Invalid session!",
    workerNotFound: "Worker not found!",
    somethingWentWrong: "Something went wrong!",
    notWorkingDay: "The day is not a working day!",
    // Comment Tags
    commentTags: {
      notWorkingDay: "Not a working day",
      alreadyClockedOut: "Already clocked out",
      beyondSiteHours: "Beyond site working hours",
      exceededDailyHours: "Exceeded daily working hours",
      didntClockOutAction: "Forgot to clock out?",
    },
    // File Upload translations
    attachments: "Attachments",
    uploadFile: "Upload File",
    takePhoto: "Take Photo",
    noFilesYet: "No files uploaded yet",
    notes: "Notes",
    // Request History Page
    requestHistory: "Request History",
    requestHistoryDesc: "View all submitted requests and their statuses",
    backToHome: "Back to Home",
    noRequests: "No requests",
    newRequestsWillAppear: "New requests will appear here",
    filterByDate: "Filter by date",
    startDate: "Start date",
    endDate: "End date",
    applyFilter: "Apply filter",
    clearFilter: "Clear filter",
    createdOn: "Created on:",
    updatedOn: "Updated on:",
    handledBy: "Handled by:",
    enterStartTime: "Enter start time",
    exitTime: "Exit time",
    // Request statuses
    approved: "Approved",
    rejected: "Rejected",
    pending: "Pending",
    // Request types
    requestTypes: {
      timeChange: "Time Change",
      timeChangeDesc: "Manual time reporting",
      sickLeave: "Sick Leave",
      sickLeaveDesc: "Report sick day",
      dayOff: "Day Off",
      dayOffDesc: "Report vacation day",
      holiday: "Holiday",
      holidayDesc: "Report holiday",
      other: "Other",
    },
  },
  ru: {
    title: "Документы, ожидающие подписания",
    welcome: "Здравствуйте",
    description:
      "У вас есть документы, ожидающие подписания. Пожалуйста, просмотрите и подпишите их.",
    status: { signed: "Подписано", waiting: "Ожидает подписания" },
    signButton: "Подписать документ",
    loading: "Загрузка...",
    noDocuments: "Нет документов для подписания",
    createdAt: "Создано:",
    passport: "Номер паспорта",
    clockIn: "Начало работы",
    clockOut: "Конец работы",
    pause: "Пауза",
    resume: "Продолжить",
    submitRequest: "Отправить запрос",
    monthlyReport: "Месячный отчет",
    mySalarySlips: "Мои расчетные листы",
    signHoursReport: "Подписать отчет о часах",
    noRecordsFound: "Записи за этот месяц не найдены",
    months: {
      january: "Январь",
      february: "Февраль",
      march: "Март",
      april: "Апрель",
      may: "Май",
      june: "Июнь",
      july: "Июль",
      august: "Август",
      september: "Сентябрь",
      october: "Октябрь",
      november: "Ноябрь",
      december: "Декабрь",
    },
    gpsRequired: "Требуется местоположение",
    gpsError: "Ошибка получения местоположения",
    requestTitle: "Выберите тип запроса",
    requestTypes: {
      timeChange: "Изменение времени",
      timeChangeDesc: "Ручной учет времени",
      sickLeave: "Больничный",
      sickLeaveDesc: "Отчет о больничном",
      dayOff: "Выходной",
      dayOffDesc: "Отчет о выходном дне",
      holiday: "Праздник",
      holidayDesc: "Отчет о празднике",
      other: "Другое",
    },
    attendance: "Посещаемость",
    browserNotSupported:
      "Ваш браузер не поддерживает определение местоположения GPS",
    locationUnavailable:
      "Местоположение GPS сейчас недоступно, попробуйте через несколько секунд",
    locationPermissionDenied:
      "Для учета посещаемости требуется разрешение на определение местоположения GPS",
    locationTimeout:
      "Время запроса местоположения GPS истекло, попробуйте еще раз",
    locationError: "Ошибка получения местоположения GPS, попробуйте еще раз",
    approve: "Подтвердить",
    edit: "Изменить",
    minutes: "мин",
    hours: "ч",
    notesPlaceholder: "Пожалуйста, укажите причину запроса...",
    close: "Закрыть",
    back: "Назад",
    notes: "Примечания",
    // Notification translations
    clockInSuccess: "Вход успешно зарегистрирован",
    clockOutSuccess: "Выход успешно зарегистрирован",
    clockInReminder: "Напоминание о начале работы",
    clockOutReminder: "Напоминание об окончании работы",
    locationPermissionDeniedDesc:
      "Пожалуйста, включите службы геолокации для учета времени",
    locationUnavailableDesc:
      "Пожалуйста, повторите попытку через несколько минут",
    notificationTitle: "Уведомление о рабочем времени",
    timeToClockIn: "Время отметить начало работы",
    timeToClockOut: "Время отметить окончание работы",
    // Permissions Modal
    permissionsRequired: "Требуются разрешения",
    permissionsDescription:
      "Для обеспечения наилучшего опыта нам нужно ваше разрешение на:",
    locationPermissionTitle: "Доступ к местоположению",
    locationPermissionDesc: "Для точной регистрации вашего присутствия",
    notificationPermissionTitle: "Push-уведомления",
    notificationPermissionDesc:
      "Для напоминания о времени начала/окончания работы",
    later: "Позже",
    unknownLocation: "Неизвестное местоположение",
    logout: "Выйти",
    logoutConfirmation: "Вы уверены, что хотите выйти?",
    confirm: "Подтвердить",
    cancel: "Отмена",
    logoutError: "Ошибка выхода",
    // Worker Daily Summary
    invalidSession: "Недействительная сессия!",
    workerNotFound: "Работник не найден!",
    somethingWentWrong: "Что-то пошло не так!",
    notWorkingDay: "Это не рабочий день!",
    // Comment Tags
    commentTags: {
      notWorkingDay: "Не рабочий день",
      alreadyClockedOut: "Уже отмечен выход",
      beyondSiteHours: "Вне рабочих часов объекта",
      exceededDailyHours: "Превышено дневное рабочее время",
      didntClockOutAction: "Не отмечен выход",
    },
    // File Upload translations
    attachments: "Вложения",
    uploadFile: "Загрузить файл",
    takePhoto: "Сделать фото",
    noFilesYet: "Файлы еще не загружены",
    notes: "Примечания",
    // Request History Page
    requestHistory: "История запросов",
    requestHistoryDesc: "Просмотрите все отправленные запросы и их статусы",
    backToHome: "Вернуться на главную страницу",
    noRequests: "Запросов нет",
    newRequestsWillAppear: "Новые запросы появятся здесь",
    filterByDate: "Фильтровать по дате",
    startDate: "Дата начала",
    endDate: "Дата окончания",
    applyFilter: "Применить фильтр",
    clearFilter: "Очистить фильтр",
    createdOn: "Создано:",
    updatedOn: "Обновлено:",
    handledBy: "Обработано:",
    enterStartTime: "Время начала",
    exitTime: "Время окончания",
    // Request statuses
    approved: "Подтвержден",
    rejected: "Отклонен",
    pending: "Ожидается подтверждение",
    // Request types
    requestTypes: {
      timeChange: "Изменение времени",
      timeChangeDesc: "Ручной учет времени",
      sickLeave: "Больничный",
      sickLeaveDesc: "Отчет о больничном",
      dayOff: "Выходной",
      dayOffDesc: "Отчет о выходном дне",
      holiday: "Праздник",
      holidayDesc: "Отчет о празднике",
      other: "Другое",
      overtime: "Дополнительные часы",
    },
  },
  ar: {
    title: "مستندات في انتظار التوقيع",
    welcome: "مرحباً",
    description:
      "لديك مستندات في انتظار التوقيع. يرجى مراجعتها والتوقيع عليها.",
    status: { signed: "موقّع", waiting: "في انتظار التوقيع" },
    signButton: "وقّع المستند",
    loading: "جاري التحميل...",
    noDocuments: "لا توجد مستندات للتوقيع",
    createdAt: "تم الإنشاء في:",
    // Sign-in translations
    verifyAccount: "تحقق من حسابك",
    enterPassword:
      "يرجى إدخال كلمة المرور المستلمة في الرسالة النصية لعرض هذا المستند.",
    submit: "إرسال",
    password: "كلمة المرور",
    // Signature translations
    clearSignature: "مسح التوقيع",
    signAllFields: "وقّع جميع الحقول",
    saveAndNext: "حفظ والتالي",
    signAndFinish: "توقيع وإنهاء",
    quickSignature: "توقيع سريع",
    selectSignatureField: "اختر حقل التوقيع",
    signaturesCompleted: "اكتملت التوقيعات",
    outOf: "من",
    page: "صفحة",
    movingToPage: "الانتقال إلى الصفحة",
    allSignaturesCompleted: "اكتملت جميع التوقيعات",
    signature: "التوقيع",
    // PDF form translations
    save: "حفظ",
    saving: "جاري الحفظ...",
    saveAndNext: "حفظ والتالي",
    moveToNextDoc: "حفظ والانتقال إلى المستند التالي",
    current: "(الحالي)",
    pleaseSignBelow: "يرجى التوقيع أدناه",
    requiredSignature: "التوقيع مطلوب في الصفحة",
    movingToNextDoc: "الانتقال إلى المستند التالي...",
    formSavedSuccess: "تم حفظ النموذج بنجاح",
    errorSavingForm: "خطأ في حفظ النموذج",
    quickFillForm: "ملء سريع للنموذج",
    complete: "إكمال",
    next: "التالي",
    back: "رجوع",
    clearAll: "مسح الكل",
    invalidCode: "رمز غير صالح. يرجى المحاولة مرة أخرى.",
    tryAgainIn: "حاول مرة أخرى في",
    seconds: "ثواني",
    codeSent: "تم إرسال رمز جديد",
    resendCode: "إعادة إرسال الرمز",
    error: "حدث خطأ. يرجى المحاولة مرة أخرى.",
    // Worker Details
    passport: "رقم جواز السفر",
    // Clock Actions
    clockIn: "تسجيل الدخول",
    clockOut: "تسجيل الخروج",
    pause: "إيقاف مؤقت",
    resume: "استئناف",
    submitRequest: "تقديم طلب",
    // Navigation
    monthlyReport: "التقرير الشهري",
    mySalarySlips: "قسائم الراتب",
    signHoursReport: "توقيع تقرير الساعات",
    // Working Hours
    noRecordsFound: "لم يتم العثور على سجلات لهذا الشهر",
    // Months
    months: {
      january: "يناير",
      february: "فبراير",
      march: "مارس",
      april: "أبريل",
      may: "مايو",
      june: "يونيو",
      july: "يوليو",
      august: "أغسطس",
      september: "سبتمبر",
      october: "أكتوبر",
      november: "نوفمبر",
      december: "ديسمبر",
    },
    // GPS Messages
    gpsRequired: "الموقع مطلوب",
    gpsError: "خطأ في الحصول على الموقع",
    // Request Modal
    requestTitle: "اختر نوع الطلب",
    requestTypes: {
      timeChange: "تغيير الوقت",
      timeChangeDesc: "تقرير الوقت اليدوي",
      sickLeave: "إجازة مرضية",
      sickLeaveDesc: "تقرير يوم مرضي",
      dayOff: "يوم إجازة",
      dayOffDesc: "تقرير يوم إجازة",
      holiday: "عطلة",
      holidayDesc: "تقرير يوم عطلة",
      other: "أخرى",
    },
    attendance: "الحضور",
    // Location Messages
    browserNotSupported: "متصفحك لا يدعم تحديد الموقع GPS",
    locationUnavailable:
      "موقع GPS غير متوفر حالياً، يرجى المحاولة مرة أخرى بعد بضع ثوان",
    locationPermissionDenied: "إذن تحديد الموقع GPS مطلوب لتسجيل الحضور",
    locationTimeout: "انتهت مهلة طلب موقع GPS، يرجى المحاولة مرة أخرى",
    locationError: "خطأ في الحصول على موقع GPS، يرجى المحاولة مرة أخرى",
    approve: "موافقة",
    edit: "تعديل",
    minutes: "دقيقة",
    hours: "ساعة",
    notesPlaceholder: "يرجى تفصيل سبب الطلب...",
    close: "إغلاق",
    // Notification translations
    clockInSuccess: "تم تسجيل الدخول بنجاح",
    clockOutSuccess: "تم تسجيل الخروج بنجاح",
    clockInReminder: "تذكير بتسجيل الدخول",
    clockOutReminder: "تذكير بتسجيل الخروج",
    locationPermissionDeniedDesc:
      "يرجى تمكين خدمات الموقع لتسجيل الدخول/الخروج",
    locationUnavailableDesc: "يرجى المحاولة مرة أخرى بعد قليل",
    notificationTitle: "إشعار وقت العمل",
    timeToClockIn: "حان وقت تسجيل الدخول",
    timeToClockOut: "حان وقت تسجيل الخروج",
    // Permissions Modal
    permissionsRequired: "الأذونات المطلوبة",
    permissionsDescription: "لتوفير أفضل تجربة لك، نحتاج إلى إذنك من أجل:",
    locationPermissionTitle: "الوصول إلى الموقع",
    locationPermissionDesc: "لتسجيل حضورك بدقة",
    notificationPermissionTitle: "الإشعارات",
    notificationPermissionDesc: "لتذكيرك بأوقات تسجيل الدخول/الخروج",
    later: "لاحقاً",
    unknownLocation: "موقع غير معروف",
    logout: "تسجيل الخروج",
    logoutConfirmation: "هل أنت متأكد أنك تريد تسجيل الخروج؟",
    confirm: "تأكيد",
    cancel: "إلغاء",
    logoutError: "خطأ في تسجيل الخروج",
    // Worker Daily Summary
    invalidSession: "!جلسة غير صالحة",
    workerNotFound: "!لم يتم العثور على العامل",
    somethingWentWrong: "!حدث خطأ ما",
    notWorkingDay: "!اليوم ليس يوم عمل",
    // Comment Tags
    commentTags: {
      notWorkingDay: "ليس يوم عمل",
      alreadyClockedOut: "تم تسجيل الخروج مسبقاً",
      beyondSiteHours: "خارج ساعات عمل الموقع",
      exceededDailyHours: "تم تجاوز ساعات العمل اليومية",
      didntClockOutAction: "لم يتم تسجيل الخروج",
    },
    // File Upload translations
    attachments: "المرفقات",
    uploadFile: "تحميل ملف",
    takePhoto: "التقاط صورة",
    noFilesYet: "لم يتم تحميل أي ملفات بعد",
    notes: "ملاحظات",
    // Request History Page
    requestHistory: "تاريخ الطلب",
    requestHistoryDesc: "رؤية جميع الطلبات التي تم تقديمها وحالاتها",
    backToHome: "العودة إلى الصفحة الرئيسية",
    noRequests: "لا توجد طلبات",
    newRequestsWillAppear: "سيظهر طلبات جديدة على هذه الصفحة",
    filterByDate: "تصفية حسب التاريخ",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    applyFilter: "تطبيق الفلتر",
    clearFilter: "مسح الفلتر",
    createdOn: "تم الإنشاء في:",
    updatedOn: "تم التحديث في:",
    handledBy: "تم التعامل بواسطة:",
    enterStartTime: "وقت الدخول",
    exitTime: "وقت الخروج",
    // Request statuses
    approved: "موافقة",
    rejected: "رفض",
    pending: "قيد الانتظار",
    // Request types
    requestTypes: {
      timeChange: "تغيير الوقت",
      timeChangeDesc: "تقرير الوقت اليدوي",
      sickLeave: "إجازة مرضية",
      sickLeaveDesc: "تقرير يوم مرضي",
      dayOff: "يوم إجازة",
      dayOffDesc: "تقرير يوم إجازة",
      holiday: "عطلة",
      holidayDesc: "تقرير يوم عطلة",
      other: "أخرى",
      overtime: "ساعات إضافية",
    },
  },
  th: {
    title: "เอกสารรอการลงนาม",
    welcome: "สวัสดี",
    description: "คุณมีเอกสารรอการลงนาม โปรดตรวจสอบและลงนาม",
    status: { signed: "ลงนามแล้ว", waiting: "รอการลงนาม" },
    signButton: "ลงนามเอกสาร",
    loading: "กำลังโหลด...",
    noDocuments: "ไม่มีเอกสารให้ลงนาม",
    createdAt: "สร้างเมื่อ:",
    // Sign-in translations
    verifyAccount: "ยืนยันบัญชีของคุณ",
    enterPassword: "กรุณาใส่รหัสผ่านที่ได้รับทาง SMS เพื่อดูเอกสารนี้",
    submit: "ส่ง",
    password: "รหัสผ่าน",
    // Signature translations
    clearSignature: "ล้างลายเซ็น",
    signAllFields: "ลงนามทุกช่อง",
    saveAndNext: "บันทึกและถัดไป",
    signAndFinish: "ลงนามและเสร็จสิ้น",
    quickSignature: "ลายเซ็นด่วน",
    selectSignatureField: "เลือกช่องลายเซ็น",
    signaturesCompleted: "ลงนามเสร็จสิ้น",
    outOf: "จาก",
    page: "หน้า",
    movingToPage: "กำลังย้ายไปหน้า",
    allSignaturesCompleted: "ลงนามครบทุกช่องแล้ว",
    signature: "ลายเซ็น",
    // PDF form translations
    save: "บันทึก",
    saving: "กำลังบันทึก...",
    saveAndNext: "บันทึกและถัดไป",
    moveToNextDoc: "บันทึกและไปยังเอกสารถัดไป",
    current: "(ปัจจุบัน)",
    pleaseSignBelow: "กรุณาลงนามด้านล่าง",
    requiredSignature: "ต้องการลายเซ็นในหน้า",
    movingToNextDoc: "กำลังย้ายไปยังเอกสารถัดไป...",
    formSavedSuccess: "บันทึกแบบฟอร์มสำเร็จ",
    errorSavingForm: "บันทึกแบบฟอร์มผิดพลัง",
    quickFillForm: "กรอกแบบฟอร์มด่วน",
    complete: "เสร็จสิ้น",
    next: "ถัดไป",
    back: "ย้อนกลับ",
    clearAll: "ล้างทั้งหมด",
    invalidCode: "รหัสไม่ถูกต้อง กรุณาลองอีกครั้ง",
    tryAgainIn: "ลองอีกครั้งใน",
    seconds: "วินาที",
    codeSent: "ส่งรหัสใหม่แล้ว",
    resendCode: "ส่งรหัสอีกครั้ง",
    error: "เกิดข้อผิดพลัง กรุณาลองอีกครั้ง",
    // Worker Details
    passport: "หมายเลขหนังสือเดินทาง",
    // Clock Actions
    clockIn: "ลงเวลาเข้า",
    clockOut: "ลงเวลาออก",
    pause: "หยุดชั่วคราว",
    resume: "ทำงานต่อ",
    submitRequest: "ส่งคำขอ",
    // Navigation
    monthlyReport: "รายงานประจำเดือน",
    mySalarySlips: "สลิปเงินเดือนของฉัน",
    signHoursReport: "ลงนามรายงานชั่วโมง",
    // Working Hours
    noRecordsFound: "ไม่พบบันทึกสำหรับเดือนนี้",
    // Months
    months: {
      january: "มกราคม",
      february: "กุมภาพันธ์",
      march: "มีนาคม",
      april: "เมษายน",
      may: "พฤษภาคม",
      june: "มิถุนายน",
      july: "กรกฎาคม",
      august: "สิงหาคม",
      september: "กันยายน",
      october: "ตุลาคม",
      november: "พฤศจิกายน",
      december: "ธันวาคม",
    },
    // GPS Messages
    gpsRequired: "GPS สถานที่จำเป็น",
    gpsError: "เกิดข้อผิดพลังการรับสถานที่",
    // Request Modal
    requestTitle: "เลือกประเภทคำขอ",
    requestTypes: {
      timeChange: "เปลี่ยนเวลา",
      timeChangeDesc: "รายงานเวลาด้วยตนเอง",
      sickLeave: "ลาป่วย",
      sickLeaveDesc: "รายงานวันลาป่วย",
      dayOff: "ลาหยุด",
      dayOffDesc: "รายงานวันลาหยุด",
      holiday: "วันหยุด",
      holidayDesc: "รายงานวันหยุด",
      other: "อื่นๆ",
    },
    attendance: "การลงเวลา",
    // Location Messages
    browserNotSupported: "เบราว์เซอร์ของคุณไม่รองรับการระบุตำแหน่ง GPS",
    locationUnavailable: "GPS สถานที่จำเป็น กรุณาลองอีกครั้งในอีกสักครู่",
    locationPermissionDenied: "ต้องได้รับอนุญาตตำแหน่ง GPS สำหรับการลงเวลา",
    locationTimeout: "GPS สถานที่จำเป็น กรุณาลองอีกครั้ง",
    locationError: "เกิดข้อผิดพลังการรับตำแหน่ง GPS กรุณาลองอีกครั้ง",
    approve: "อนุมัติ",
    edit: "แก้ไข",
    minutes: "นาที",
    hours: "ชั่วโมง",
    notesPlaceholder: "โปรดระบุเหตุผลของคำขอโดยละเอียด...",
    close: "ปิด",
    // Notification translations
    clockInSuccess: "ลงเวลาเข้างานสำเร็จ",
    clockOutSuccess: "ลงเวลาออกงานสำเร็จ",
    clockInReminder: "แจ้งเตือนลงเวลาเข้างาน",
    clockOutReminder: "แจ้งเตือนลงเวลาออกงาน",
    locationPermissionDeniedDesc: "กรุณาเปิดใช้งานบริการระบุตำแหน่งเพื่อลงเวลา",
    locationUnavailableDesc: "กรุณาลองใหม่อีกครั้งในอีกสักครู่",
    notificationTitle: "แจ้งเตือนเวลาทำงาน",
    timeToClockIn: "ถึงเวลาลงเวลาเข้างาน",
    timeToClockOut: "ถึงเวลาลงเวลาออกงาน",
    // Permissions Modal
    permissionsRequired: "ต้องการสิทธิ์",
    permissionsDescription:
      "เพื่อมอบประสบการณ์ที่ดีที่สุด เราต้องการสิทธิ์จากคุณสำหรับ:",
    locationPermissionTitle: "การเข้าถึงตำแหน่ง",
    locationPermissionDesc: "เพื่อบันทึกการเข้างานของคุณอย่างแม่นยำ",
    notificationPermissionTitle: "การแจ้งเตือนแบบพุช",
    notificationPermissionDesc: "เพื่อเตือนคุณเกี่ยวกับเวลาลงเวลาเข้า/ออก",
    later: "ภายหลัง",
    unknownLocation: "ตำแหน่งที่ไม่รู้จัก",
    logout: "ออกจากระบบ",
    logoutConfirmation: "คุณแน่ใจหรือไม่ว่าต้องการออกจากระบบ?",
    confirm: "ยืนยัน",
    cancel: "ยกเลิก",
    logoutError: "เกิดข้อผิดพลาดในการออกจากระบบ",
    // Worker Daily Summary
    invalidSession: "เซสชันไม่ถูกต้อง!",
    workerNotFound: "ไม่พบคนงาน!",
    somethingWentWrong: "เกิดข้อผิดพลาด!",
    notWorkingDay: "ไม่ใช่วันทำงาน!",
    // Comment Tags
    commentTags: {
      notWorkingDay: "ไม่ใช่วันทำงาน",
      alreadyClockedOut: "ลงเวลาออกแล้ว",
      beyondSiteHours: "นอกเวลาทำงานของไซต์",
      exceededDailyHours: "เกินชั่วโมงทำงานต่อวัน",
      didntClockOutAction: "ลืมลงเวลาออก?",
    },
    // File Upload translations
    attachments: "ไฟล์แนบ",
    uploadFile: "อัปโหลดไฟล์",
    takePhoto: "ถ่ายภาพ",
    noFilesYet: "ยังไม่มีไฟล์ที่อัปโหลด",
    notes: "หมายเหตุ",
    // Request History Page
    requestHistory: "ประวัติการส่งคำขอ",
    requestHistoryDesc: "ดูประวัติการส่งคำขอทั้งหมดและสถานะของคำขอ",
    backToHome: "กลับไปยังหน้าหลัก",
    noRequests: "ไม่มีคำขอ",
    newRequestsWillAppear: "คำขอใหม่จะปรากฏที่นี่",
    filterByDate: "กรองตามวันที่",
    startDate: "วันที่เริ่ม",
    endDate: "วันที่สิ้นสุด",
    applyFilter: "นำคำขอที่กรองมาใช้",
    clearFilter: "ล้างคำขอที่กรองแล้ว",
    createdOn: "สร้างเมื่อ:",
    updatedOn: "อัปเดตเมื่อ:",
    handledBy: "จัดการโดย:",
    enterStartTime: "เวลาที่เข้างาน",
    exitTime: "เวลาที่ออกงาน",
    // Request statuses
    approved: "อนุมัติ",
    rejected: "ปฏิเสธ",
  },
  si: {
    title: "අත්සන් කිරීමට ඇති ලේඛන",
    welcome: "ආයුබෝවන්",
    description: "ඔබට අත්සන් කිරීමට ලේඛන ඇත. කරුණාකර සමාලෝචනය කර අත්සන් කරන්න.",
    status: { signed: "අත්සන් කර ඇත", waiting: "අත්සන් කිරීමට නියමිතයි" },
    signButton: "ලේඛනයට අත්සන් කරන්න",
    loading: "පූරණය වෙමින්...",
    noDocuments: "අත්සන් කිරීමට ලේඛන නැත",
    createdAt: "නිර්මාණය කළ දිනය:",
    // Sign-in translations
    verifyAccount: "ඔබගේ ගිණුම තහවුරු කරන්න",
    enterPassword:
      "මෙම ලේඛනය බැලීමට කෙටි පණිවිඩයෙන් ලැබුණු මුරපදය ඇතුළත් කරන්න.",
    submit: "යොමු කරන්න",
    password: "මුරපදය",
    // Signature translations
    clearSignature: "අත්සන මකන්න",
    signAllFields: "සියලු ක්ෂේත්‍රවලට අත්සන් කරන්න",
    saveAndNext: "සුරකින්න සහ ඊළඟ",
    signAndFinish: "අත්සන් කර අවසන් කරන්න",
    quickSignature: "ක්ෂණික අත්සන",
    selectSignatureField: "අත්සන් ක්ෂේත්‍රය තෝරන්න",
    signaturesCompleted: "අත්සන් සම්පූර්ණයි",
    outOf: "න්",
    page: "පිටුව",
    movingToPage: "පිටුවට යමින්",
    allSignaturesCompleted: "සියලු අත්සන් සම්පූර්ණයි",
    signature: "අත්සන",
    // PDF form translations
    save: "සුරකින්න",
    saving: "සුරකිමින්...",
    saveAndNext: "සුරකින්න සහ ඊළඟ",
    moveToNextDoc: "සුරකින්න සහ ඊළඟ ලේඛනයට යන්න",
    current: "(වත්මන්)",
    pleaseSignBelow: "කරුණාකර පහතින් අත්සන් කරන්න",
    requiredSignature: "පිටුවේ අත්සන අවශ්‍යයි",
    movingToNextDoc: "ඊළඟ ලේඛනයට යමින්...",
    formSavedSuccess: "පෝරමය සාර්ථකව සුරකින ලදී",
    errorSavingForm: "පෝරමය සුරැකීමේ දෝෂයක්",
    quickFillForm: "ක්ෂණික පිරවීම",
    complete: "සම්පූර්ණයි",
    next: "ඊළඟ",
    back: "ආපසු",
    clearAll: "සියල්ල මකන්න",
    invalidCode: "වලංගු නොවන කේතයකි. නැවත උත්සාහ කරන්න.",
    tryAgainIn: "නැවත උත්සාහ කරන්න",
    seconds: "තත්පර",
    codeSent: "නව කේතය යවා ඇත",
    resendCode: "කේතය නැවත යවන්න",
    error: "දෝෂයක් සිදු විය. නැවත උත්සාහ කරන්න.",
    // Worker Details
    passport: "ගමන් බලපත්‍ර අංකය",
    // Clock Actions
    clockIn: "පැමිණීම සටහන් කරන්න",
    clockOut: "පිටවීම සටහන් කරන්න",
    pause: "විරාමය",
    resume: "නැවත ආරම්භ කරන්න",
    submitRequest: "ඉල්ලීම යොමු කරන්න",
    // Navigation
    monthlyReport: "මාසික වාර්තාව",
    mySalarySlips: "මගේ වැටුප් පත්‍රිකා",
    signHoursReport: "පැය වාර්තාව අත්සන් කරන්න",
    // Working Hours
    noRecordsFound: "මෙම මාසය සඳහා වාර්තා නොමැත",
    // Months
    months: {
      january: "ජනවාරි",
      february: "පෙබරවාරි",
      march: "මාර්තු",
      april: "අප්‍රේල්",
      may: "මැයි",
      june: "ජූනි",
      july: "ජූලි",
      august: "අගෝස්තු",
      september: "සැප්තැම්බර්",
      october: "ඔක්තෝබර්",
      november: "නොවැම්බර්",
      december: "දෙසැම්බර්",
    },
    // GPS Messages
    gpsRequired: "GPS ස්ථානය අවශ්‍යයි",
    gpsError: "ස්ථානය ලබා ගැනීමේ දෝෂයක්",
    // Request Modal
    requestTitle: "ඉල්ලීම් වර්ගය තෝරන්න",
    requestTypes: {
      timeChange: "වේලාව වෙනස් කිරීම",
      timeChangeDesc: "අතින් වේලාව වාර්තා කිරීම",
      sickLeave: "ලෙඩ නිවාඩු",
      sickLeaveDesc: "ලෙඩ දිනය වාර්තා කරන්න",
      dayOff: "නිවාඩු දිනය",
      dayOffDesc: "නිවාඩු දිනය වාර්තා කරන්න",
      holiday: "නිවාඩු",
      holidayDesc: "නිවාඩු දිනය වාර්තා කරන්න",
      other: "වෙනත්",
    },
    attendance: "පැමිණීම",
    // Location Messages
    browserNotSupported: "ඔබගේ බ්‍රවුසරය GPS ස්ථානය සඳහා සහය නොදක්වයි",
    locationUnavailable:
      "GPS ස්ථානය දැනට ලබා ගත නොහැක, කරුණාකර තත්පර කිහිපයකින් නැවත උත්සාහ කරන්න",
    locationPermissionDenied: "පැමිණීම සඳහා GPS ස්ථාන අවසරය අවශ්‍ය වේ",
    locationTimeout:
      "GPS ස්ථානය ලබා ගැනීමේ කාලය අවසන්, කරුණාකර නැවත උත්සාහ කරන්න",
    locationError: "GPS ස්ථානය ලබා ගැනීමේ දෝෂයක්, කරුණාකර නැවත උත්සාහ කරන්න",
    approve: "අනුමත කරන්න",
    edit: "සංස්කරණය",
    minutes: "මිනිත්තු",
    hours: "පැය",
    notesPlaceholder: "කරුණාකර ඉල්ලීමේ හේතුව විස්තර කරන්න...",
    close: "වසන්න",
    // Notification translations
    clockInSuccess: "පැමිණීම සාර්ථකයි",
    clockOutSuccess: "පිටවීම සාර්ථකයි",
    clockInReminder: "පැමිණීමේ සිහිකැඳවීම",
    clockOutReminder: "පිටවීමේ සිහිකැඳවීම",
    locationPermissionDeniedDesc:
      "පැමිණීම/පිටවීම සඳහා ස්ථාන සේවා සක්‍රිය කරන්න",
    locationUnavailableDesc: "කරුණාකර මොහොතකින් නැවත උත්සාහ කරන්න",
    notificationTitle: "වැඩ කාල දැනුම්දීම",
    timeToClockIn: "පැමිණීම වාර්තා කරන වේලාව",
    timeToClockOut: "පිටවීම වාර්තා කරන වේලාව",
    // Permissions Modal
    permissionsRequired: "අවසර අවශ්‍යයි",
    permissionsDescription:
      "ඔබට හොඳම අත්දැකීමක් ලබා දීමට, අපට ඔබගේ අවසරය අවශ්‍යයි:",
    locationPermissionTitle: "ස්ථාන ප්‍රවේශය",
    locationPermissionDesc: "ඔබගේ පැමිණීම නිවැරදිව වාර්තා කිරීමට",
    notificationPermissionTitle: "පුෂ් දැනුම්දීම්",
    notificationPermissionDesc: "පැමිණීමේ/පිටවීමේ වේලාවන් ගැන මතක් කිරීමට",
    later: "පසුව",
    unknownLocation: "නොදන්නා ස්ථානයක්",
    logout: "පිටවීම",
    logoutConfirmation: "ඔබට පිටවීමට අවශ්‍ය බව විශ්වාසද?",
    confirm: "තහවුරු කරන්න",
    cancel: "අවලංගු කරන්න",
    logoutError: "පිටවීමේ දෝෂයක්",
    // Worker Daily Summary
    invalidSession: "වලංගු නොවන සැසිය!",
    workerNotFound: "සේවකයා හමු නොවීය!",
    somethingWentWrong: "යමක් වැරදී ඇත!",
    notWorkingDay: "මෙය වැඩ කරන දිනයක් නොවේ!",
    // Comment Tags
    commentTags: {
      notWorkingDay: "වැඩ කරන දිනයක් නොවේ",
      alreadyClockedOut: "දැනටමත් පිටවීම සටහන් කර ඇත",
      beyondSiteHours: "වැඩබිමේ වැඩ කරන වේලාවෙන් පිටත",
      exceededDailyHours: "දෛනික වැඩ කරන පැය ගණන ඉක්මවා ඇත",
      didntClockOutAction: "පිටවීම සටහන් කර නැත",
    },
    // File Upload translations
    attachments: "ඇමුණුම්",
    uploadFile: "ගොනුව උඩුගත කරන්න",
    takePhoto: "ඡායාරූපයක් ගන්න",
    noFilesYet: "තවම ගොනු උඩුගත කර නැත",
    notes: "සටහන්",
    // Request History Page
  },
};
